add turn link in pre div option, and set it to default true
PaeP3nguin/LinkBot pull request #5
Opened 2019-01-03 13:00 UTC by fucusy

Problem:
We met some request to enable to turn plain text to link in <pre>, 
 https://github.com/PaeP3nguin/LinkBot/issues/2,  and https://github.com/PaeP3nguin/LinkBot/issues/3

Solution:
I add an option to enable that, and the default behavior is turning the plain text to link in <pre>.

2019-01-04 03:33 UTC, PaeP3nguin commented
Thanks for the PR! I'll have time to review it this weekend

2019-01-05 07:43 UTC, fucusy commented
Thanks for your time.

2019-01-07 03:38 UTC, PaeP3nguin requested changes
Looks good! Just a few small comments. Thanks for submitting this PR!

2019-01-07 03:38 UTC, PaeP3nguin commented on content_scripts/main.js
> +  if (EXCLUDED_TAGS.hasOwnProperty(node.tagName) && EXCLUDED_TAGS[node.tagName] || isNodeEditable(node)) {
Now that we're actually using the true/false value inside EXCLUDED_TAGS, let's just get rid of the "hasOwnProperty" check. If the tag we're checking isn't in EXCLUDED_TAGS, it should return undefined anyways, which is fine.

2019-01-07 03:38 UTC, PaeP3nguin commented on content_scripts/main.js
> +      if (EXCLUDED_TAGS.hasOwnProperty(node.tagName) && EXCLUDED_TAGS[node.tagName]) {
Same here, let's just get rid of the hasOwnProperty check

2019-01-07 03:38 UTC, PaeP3nguin commented on options/options.html
> +            <label><input id="linkOnPre" type="checkbox">Turn link in &lt;pre&gt;</label>
Can we reword the description to: "Convert links inside preformatted text blocks (\<pre> tag)"

Hopefully it'll help non-devs understand what the option does a little better :)

2019-01-07 03:38 UTC, PaeP3nguin commented on manifest.json
> +   "version": "1.0.7",
Could you also update the version in package.json? That version doesn't really do anything and it's been out of date (oops) but might as well keep the two in sync.

2019-01-07 03:40 UTC, fucusy commented
Thanks, I will fix them soon

2019-01-07 04:41 UTC, fucusy commented
@PaeP3nguin I fixed them, could you take a look at the PR again

2019-01-07 05:19 UTC, PaeP3nguin approved these changes

2019-01-07 05:19 UTC, merged